# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Theme settings
theme: jekyll-theme-modernist

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Custom CSS

# Search functionality
search_enabled: true
search_provider: lunr
search_index_path: /docs/assets/lunr_index.json
