# Site settings
title: Freddy Store API Documentation
description: A comprehensive guide to using our APIs.
baseurl: /docs
url: https://nermineabdulhafiz.github.io

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Navigation menu
navigation:
  - title: User Guide
    url: /docs/user-guide.md

  - title: API Reference
    url: /docs/api-reference.md

# Theme settings
theme: jekyll-theme-minimal

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Custom CSS

# Search functionality
search_enabled: true
search_provider: lunr
search_index_path: /docs/assets/lunr_index.json
